default[:leiningen][:version] = "2.5.0"
default[:leiningen][:install_script] = "https://github.com/technomancy/leiningen/raw/#{leiningen[:version]}/bin/lein"
default[:leiningen][:user] = "chef"
default[:leiningen][:group] = "root"
default[:leiningen][:jar_dir] = "/usr/share/java"
